# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Rainfall Calculation.py
# Created on: 2026-01-13 00:02:35.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Rainfall Calculation <CHIRPS_Folder> <Clip_Area> <CHIRPS_Range__Start__YYYYMM_> <CHIRPS_Range__End__YYYYMM_> <Output_Coordinate_System> <Aggregation_Type> <Classification_interval> <Output_Feature_Class> <Z_value_field> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("C:/Users/User/Documents/PERSONAL/Portfolio/Peta/RAINFALL.tbx")
arcpy.ImportToolbox("C:/Users/User/Documents/PERSONAL/Portfolio/Peta/Rainfall Calculation.tbx")

# Script arguments
CHIRPS_Folder = arcpy.GetParameterAsText(0)
if CHIRPS_Folder == '#' or not CHIRPS_Folder:
    CHIRPS_Folder = "C:\\Users\\User\\Documents\\PERSONAL\\Portfolio\\Peta\\Curah Hujan\\CHIRPS" # provide a default value if unspecified

Clip_Area = arcpy.GetParameterAsText(1)
if Clip_Area == '#' or not Clip_Area:
    Clip_Area = "Batas_KNG" # provide a default value if unspecified

CHIRPS_Range__Start__YYYYMM_ = arcpy.GetParameterAsText(2)
if CHIRPS_Range__Start__YYYYMM_ == '#' or not CHIRPS_Range__Start__YYYYMM_:
    CHIRPS_Range__Start__YYYYMM_ = "201401" # provide a default value if unspecified

CHIRPS_Range__End__YYYYMM_ = arcpy.GetParameterAsText(3)
if CHIRPS_Range__End__YYYYMM_ == '#' or not CHIRPS_Range__End__YYYYMM_:
    CHIRPS_Range__End__YYYYMM_ = "202312" # provide a default value if unspecified

Output_Coordinate_System = arcpy.GetParameterAsText(4)
if Output_Coordinate_System == '#' or not Output_Coordinate_System:
    Output_Coordinate_System = "PROJCS['WGS_1984_UTM_Zone_49S',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',10000000.0],PARAMETER['Central_Meridian',111.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]" # provide a default value if unspecified

Aggregation_Type = arcpy.GetParameterAsText(5)
if Aggregation_Type == '#' or not Aggregation_Type:
    Aggregation_Type = "annual_average" # provide a default value if unspecified

Classification_interval = arcpy.GetParameterAsText(6)
if Classification_interval == '#' or not Classification_interval:
    Classification_interval = "500" # provide a default value if unspecified

Output_Feature_Class = arcpy.GetParameterAsText(7)
if Output_Feature_Class == '#' or not Output_Feature_Class:
    Output_Feature_Class = "C:\\Users\\User\\Documents\\PERSONAL\\Portfolio\\Rainfall\\rainfallscratch.gdb\\ReclassToPolygon_SmoothPolyg" # provide a default value if unspecified

Z_value_field = arcpy.GetParameterAsText(8)
if Z_value_field == '#' or not Z_value_field:
    Z_value_field = "GRID_CODE" # provide a default value if unspecified

# Local variables:
extracted_points = "C:\\Users\\User\\Documents\\PERSONAL\\Portfolio\\Rainfall\\rainfall.gdb\\extracted_points"
Output_cell_size = "30"
v_scratchGDB__IDW_rainfall__n_ = "C:\\Users\\User\\Documents\\PERSONAL\\Portfolio\\Rainfall\\rainfall.gdb\\Idw_rainfall"
v_scratchGDB__reclassed_polygon__n_ = "C:\\Users\\User\\Documents\\PERSONAL\\Portfolio\\Rainfall\\rainfallscratch.gdb\\ReclassToPolygon"

# Process: extracted points
arcpy.gp.toolbox = "C:/Users/User/Documents/PERSONAL/Portfolio/Peta/Rainfall Calculation.tbx";
# Warning: the toolbox C:/Users/User/Documents/PERSONAL/Portfolio/Peta/Rainfall Calculation.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.Model3(...) with arcpy.Model3_ALIAS(...)
arcpy.gp.Model3(Clip_Area, extracted_points, Output_Coordinate_System, CHIRPS_Folder, CHIRPS_Range__Start__YYYYMM_, CHIRPS_Range__End__YYYYMM_, Aggregation_Type)

# Process: IDW
arcpy.gp.Idw_sa(extracted_points, Z_value_field, v_scratchGDB__IDW_rainfall__n_, Output_cell_size, "2", "VARIABLE 12", "")

# Process: ReclassToPolygon
arcpy.gp.toolbox = "C:/Users/User/Documents/PERSONAL/Portfolio/Peta/RAINFALL.tbx";
# Warning: the toolbox C:/Users/User/Documents/PERSONAL/Portfolio/Peta/RAINFALL.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.ReclassToPolygon(...) with arcpy.ReclassToPolygon_ALIAS(...)
arcpy.gp.ReclassToPolygon(v_scratchGDB__IDW_rainfall__n_, Classification_interval, v_scratchGDB__reclassed_polygon__n_)

# Process: Smooth Polygon
arcpy.SmoothPolygon_cartography(v_scratchGDB__reclassed_polygon__n_, Output_Feature_Class, "PAEK", "10 Meters", "FIXED_ENDPOINT", "NO_CHECK", "")

